<?php

namespace Database\Seeders;

use App\Models\Admin\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run()
    {
        City::insert([
            [
                'name'=>'Akurana'
            ],
            [
                'name'=>'Aladeniya'
            ],
            [
                'name'=>'Alawathugoda'
            ],
            [
                'name'=>'Aludeniya'
            ],
            [
                'name'=>'Ambatenna'
            ],
            [
                'name'=>'Ampitiya'
            ],
            [
                'name'=>'Ankumbura'
            ],
            [
                'name'=>'Aruppola'
            ],
            [
                'name'=>'Atabage'
            ],
            [
                'name'=>'Balana'
            ],
            [
                'name'=>'Batugoda'
            ],
            [
                'name'=>'Bawlana'
            ],
            [
                'name'=>'Bopana'
            ],
            [
                'name'=>'Danthure
'
            ],
            [
                'name'=>'Daulagala'
            ],
            [
                'name'=>'Dedunupitiya'
            ],
            [
                'name'=>'Deltota'
            ],
            [
                'name'=>'Digana'
            ],
            [
                'name'=>'Doluwa'
            ],
            [
                'name'=>'Doragamuwa'
            ],
            [
                'name'=>'Ethulgama'
            ],
            [
                'name'=>'Galaboda'
            ],
            [
                'name'=>'Galagedara'
            ],
            [
                'name'=>'Galaha'
            ],
            [
                'name'=>'Galhinna'
            ],
            [
                'name'=>'Gampola'
            ],
            [
                'name'=>'Gelioya'
            ],
            [
                'name'=>'Godamunna'
            ],
            [
                'name'=>'Gonagantenna'
            ],
            [
                'name'=>'Guhagoda'
            ],
            [
                'name'=>'Gunnepana'
            ],
            [
                'name'=>'Gurudeniya'
            ],
            [
                'name'=>'Haguranketha'
            ],
            [
                'name'=>'Halloluwa'
            ],
            [
                'name'=>'Handaganawa'
            ],
            [
                'name'=>'Handessa'
            ],
            [
                'name'=>'Hanguranketha'
            ],
            [
                'name'=>'Haragama'
            ],
            [
                'name'=>'Harankahawa'
            ],
            [
                'name'=>'Harispattuwa'
            ],
            [
                'name'=>'Hasalaka'
            ],
            [
                'name'=>'Hewaheta'
            ],
            [
                'name'=>'Hindagala'
            ],
            [
                'name'=>'Hondiyadeniya'
            ],
            [
                'name'=>'Hunnasgiriya'
            ],
            [
                'name'=>'Jambugahapitiya'
            ],
            [
                'name'=>'Kadugannawa'
            ],
            [
                'name'=>'Kahataliyadda'
            ],
            [
                'name'=>'Kalugala'
            ],
            [
                'name'=>'Kandy Town'
            ],
            [
                'name'=>'Kapuliyadde'
            ],
            [
                'name'=>'Karandagolla'
            ],
            [
                'name'=>'Katugastota'
            ],
            [
                'name'=>'Kengalla'
            ],
            [
                'name'=>'Ketakumbura'
            ],
            [
                'name'=>'Kiribathkumbura'
            ],
            [
                'name'=>'Kolongoda'
            ],
            [
                'name'=>'Kulugammana'
            ],
            [
                'name'=>'Kumbukkandura'
            ],
            [
                'name'=>'Kundasale'
            ],
            [
                'name'=>'Leemagahakotuwa'
            ],
            [
                'name'=>'Lewella'
            ],
            [
                'name'=>'Lunuketiya Maditta'
            ],
            [
                'name'=>'Madawala'
            ],
            [
                'name'=>'Madugalla'
            ],
            [
                'name'=>'Madulkele'
            ],
            [
                'name'=>'Mahadoraliyadda'
            ],
            [
                'name'=>'Mahaiyawa'
            ],
            [
                'name'=>'Mahamedagama'
            ],
            [
                'name'=>'Mallapitiya'
            ],
            [
                'name'=>'Makuldeniya'
            ],
            [
                'name'=>'Mandaram Nuwara'
            ],
            [
                'name'=>'Marassana'
            ],
            [
                'name'=>'Maturata'
            ],
            [
                'name'=>'Mawatura'
            ],
            [
                'name'=>'Mawlimada'
            ],
            [
                'name'=>'Medamahanuwara'
            ],
            [
                'name'=>'Medawala harispattuwa'
            ],
            [
                'name'=>'Menikdiwela'
            ],
            [
                'name'=>'Menikhinne'
            ],
            [
                'name'=>'Mimure'
            ],
            [
                'name'=>'Minigamuwa'
            ],
            [
                'name'=>'Minipe'
            ],
            [
                'name'=>'Muruthalawa'
            ],
            [
                'name'=>'Naranpanawa'
            ],
            [
                'name'=>'Nattarampotha'
            ],
            [
                'name'=>'Nawalapitiya'
            ],
            [
                'name'=>'Nugaliyadda'
            ],
            [
                'name'=>'Nugawela'
            ],
            [
                'name'=>'Pallekele'
            ],
            [
                'name'=>'Pallekotuwa'
            ],
            [
                'name'=>'Panwilatenna'
            ],
            [
                'name'=>'Paradeka'
            ],
            [
                'name'=>'Pasbage'
            ],
            [
                'name'=>'Pattitalawa'
            ],
            [
                'name'=>'Peradeniya'
            ],
            [
                'name'=>'Pilawala'
            ],
            [
                'name'=>'Pilimathawa'
            ],
            [
                'name'=>'Poholiyadda'
            ],
            [
                'name'=>'Polgolla'
            ],
            [
                'name'=>'Poththapitiya'
            ],
            [
                'name'=>'Pujapitiya'
            ],
            [
                'name'=>'Pupuressa'
            ],
            [
                'name'=>'Pussellawa'
            ],
            [
                'name'=>'Rajawella'
            ],
            [
                'name'=>'Rambukpitiya'
            ],
            [
                'name'=>'Rangala'
            ],
            [
                'name'=>'Rantembe'
            ],
            [
                'name'=>'Rathukohodigala'
            ],
            [
                'name'=>'Rikillagaskada'
            ],
            [
                'name'=>'Sangarajapura'
            ],
            [
                'name'=>'Senarathwela'
            ],
            [
                'name'=>'Talatuoya'
            ],
            [
                'name'=>'Teldeniya'
            ],
            [
                'name'=>'Thalathuoya'
            ],
            [
                'name'=>'Thawalanthenna'
            ],
            [
                'name'=>'Thenne kubura'
            ],
            [
                'name'=>'Udahentenna'
            ],
            [
                'name'=>'Udahingulwala'
            ],
            [
                'name'=>'Uda Peradeniya'
            ],
            [
                'name'=>'Udawatta'
            ],
            [
                'name'=>'Ududumbara'
            ],
            [
                'name'=>'Uduwa'
            ],
            [
                'name'=>'Uduwahinna'
            ],
            [
                'name'=>'Uduwela'
            ],
            [
                'name'=>'Ulapane'
            ],
            [
                'name'=>'Ulpothagama'
            ],
            [
                'name'=>'Velamboda'
            ],
            [
                'name'=>'Wattappola'
            ],
            [
                'name'=>'Wattegama'
            ],
            [
                'name'=>'Weligalla'
            ],
            [
                'name'=>'Weligampola'
            ],
            [
                'name'=>'Wendaruwa'
            ],
            [
                'name'=>'Werellagama'
            ],
            [
                'name'=>'Wettawa'
            ],
            [
                'name'=>'Wilangama'
            ],
            [
                'name'=>'Yahalatenna'
            ],
            [
                'name'=>'Yatihalgala'
            ]
    ]);
    }
}
